# Generated by Django 3.0.4 on 2020-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
